### ISSUE TITLE
权重文件是哪个数据集训练出来的

### ISSUE THREAD

**Issue by deng1604** [jhb86253817/PromptMRG#1]
作者你在介绍时说：
或者，您可以从[此处](https://drive.google.com/file/d/1s4AoLnnGOysOQkdILhhFCL59LyQtRHGa/view?usp=drive_link)下载经过训练的模型权重。请注意，此模型权重是使用 [R2Gen](https://github.com/zhjohnchan/R2Gen) 的图像训练的。如果您使用自己处理的图像，则此权重可能会降低性能。在这种情况下，您需要自己训练模型。

请问，您给出的模型的权重文件，是MIMIC数据集的还是IU Xray数据集对应的权重文件呢

**Comment by deng1604** [comment]
另外，缺少训练train_iu_xray.sh文件。测试时，--load_pretrained results/promptmrg/model_best.pth
这个文件也缺少，作者可以提供下吗，不胜感激！

**Comment by jhb86253817** [comment]
你好，我给出的权重是在MIMIC上训练的。我们没有在IU上训练，而是直接用MIMIC训的模型在IU上测。更多细节可以从论文里找到，谢谢～

**Comment by deng1604** [comment]
> 你好，我给出的权重是在MIMIC上训练的。我们没有在IU上训练，而是直接用MIMIC训的模型在IU上测。更多细节可以从论文里找到，谢谢～

好的，谢谢你❤

**Comment by nobottle** [comment]
Is it possible that the MIMIC data downloaded from R2gen contains images processed differently from the MiMIC images provided on the physionet site? Or is it just the MIMIC annotation files?

**Comment by jhb86253817** [comment]
> Is it possible that the MIMIC data downloaded from R2gen contains images processed differently from the MiMIC images provided on the physionet site? Or is it just the MIMIC annotation files?

Yes, I think the images from R2Gen has been processed, which is slightly different from the images of physionet. The trained model weight I provided is trained on R2Gen images.
