### ISSUE TITLE
Lower Evaluation Results on IU X-Ray Dataset

### ISSUE THREAD

**Issue by iamsanaullah** [jhb86253817/PromptMRG#19]
We got similar results to the paper when testing the model on MIMIC-CXR, but our results on the IU X-Ray dataset were much lower than expected. Could you help us understand what might be causing this? Any advice on specific settings or configurations for the IU X-Ray dataset would be helpful.

test_BLEU_1           : 0.3200068029186167
test_BLEU_2           : 0.18665663023749204
test_BLEU_3           : 0.11578884510610013
test_BLEU_4           : 0.0758325487995331
test_METEOR           : 0.16355785734051434
test_ROUGE_L          : 0.28073069480194984
test_ce_precision     : 0.20096769033099145
test_ce_recall        : 0.19627319257837492
test_ce_f1            : 0.19060531060558145

**Comment by MUZAMIL-KHATTAK** [comment]
I am encountering the same issue and have reached out to the authors at the email addresses provided in the paper but have not received a response.
